services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}
    networks:
      - deploy_network
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge
